server:
  port: 8010
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/article_system?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis
mybatis-plus:
  type-aliases-package: com.sjdf.article.entity
  # 指定mybatis映射文件的位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 开启驼峰命名转换（开启后需要注意字段写法，不然返回值为null）
    map-underscore-to-camel-case: true
    # 替换log实现类
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      id-type: AUTO

#showSql
logging:
  level:
    com.sjdf.article.dao: debug

